#### express错误处理

##### 1.debug

使用google出品的`ndb`调试node程序

* 安装

  全局安装：`npm i -g ndb`

  局部安装：`npm i --save-dev ndb`

* 使用

  配置`package.json`

  ```json
  
    "scripts": {
      "start": "nodemon server.js",
      "prd": "NODE_ENV=production nodemon server.js",
      "dev": "NODE_ENV=development nodemon server.js",
      "debug": "ndb server.js" // 配置
    },
  ```

  

##### 2.处理错误URL

```javascript
app.use("/api/v1/user", usersRouter);
app.use("/api/v1/tours", tourRouter);

// 处理错误URL
app.use("*", (req, res) => {
  res
    .status(404)
    .json({ status: "fail", message: `${req.originalUrl} 不存在` });
});
```

之前路由都不匹配，说明URL不存在，则进入该中间件，返回错误信息



##### 3.错误处理优化

* 创建错误处理类`untils/errorHanding.js`

```javascript
class ErrorHanding extends Error {
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith(4) ? "fail" : " error";
    // 创建错误 保存在 ErrorHanding.stack 中 ，报出错误具体出现在哪个位置
    Error.captureStackTrace(this, this.constructor);
  }
}

module.exports = ErrorHanding;
```

**Error.captureStackTrace 作用：**

隐藏内部的实现细节，优化错误栈

Error.captureStackTrace 是 Node.js 提供的一个 API，可以传入两个参数：

```javascript
Error.captureStackTrace(targetObject[, constructorOpt])
```

Error.captureStackTrace 会在 targetObject 中添加一个 stack 属性，对该属性进行访问时，将以字符串的形式返回 Error.captureStackTrace() 语句被调用时的代码位置信息（即：调用栈历史）。

除了 targetObject，captureStackTrace 还接收一个类型为 function 的可选参数 constructorOpt，当传递该参数时，调用栈中所有 constructorOpt 函数之上的信息(包括 constructorOpt 函数自身)，都会在访问 targetObject.stack 时被忽略。当需要对终端用户隐藏内部的实现细节时，constructorOpt 参数会很有用。传入第 2 个参数通常用于自定义错误，例如：

```shell
function MyError() {  Error.captureStackTrace(this, MyError)  this.name = this.constructor.name  this.message = 'you got MyError'}const myError = new MyError()console.log(myError)console.log(myError.stack)// 输出MyError { name: 'MyError', message: 'you got MyError' }Error    at Object.<anonymous> (/Users/nswbmw/Desktop/test/app.js:7:17)    at ...
```

如果去掉 captureStackTrace 的第 2 个参数：

```shell
function MyError() {  Error.captureStackTrace(this)  this.name = this.constructor.name  this.message = 'you got MyError'}const myError = new MyError()console.log(myError)console.log(myError.stack)// 输出MyError { name: 'MyError', message: 'you got MyError' }Error    at new MyError (/Users/nswbmw/Desktop/test/app.js:2:9)    at Object.<anonymous> (/Users/nswbmw/Desktop/test/app.js:7:17)    at ...
```

**可以看出**：出现了 MyError 相关的调用栈，但我们并不关心 MyError 及其内部是如何实现的。



* 创建中间件

  ```javascript
  const ErrorHanding = require("./utils/errorHanding");
  const errorCon = require("./controller/errorController");
  // 处理错误URL
  app.use("*", (req, res, next) => {
    // 跳转至处理错误的中间件
    next(new ErrorHanding(`${req.originalUrl} is not found`, 404));
  });
  app.use(errorCon);
  ```

  `controller/errorController.js`

  ```javascript
  module.exports = (err, req, res, next) => {
    console.log("error controller");
    err.statusCode = err.statusCode || 500;
    err.status = err.status || "error";
    res.status(err.statusCode).json({ status: err.status, message: err.message });
  };
  ```



##### 4.优化try catch

因为 async await 出错时可以使用catch捕获错误, 所以可以讲 try catch 转换为 async await

```javascript
const catchAsync = (fn) => {
  return async (req, res, next) => {
    fn(req, res, next).catch(next); //next 本位为一个函数:（err） => {}
  };
};

//创建旅游数据
exports.createTour = catchAsync(async (req, res, next) => {
  const tourData = await Tour.create(req.body);
  res.status(200).json({ status: "create success", data: { data: tourData } });
});

//之前代码
 try {
    const data = await Tour.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
      //开启数据验证
      runValidators: true,
    });
    //new: true返回更新后的数据返回
    //runValidators: 验证更新值的type是否符合要求
    res.status(200).json({ status: "update success", data: { data: data } });
  } catch (err) {
    res.status(400).json({ status: "fail", message: err });
  }
```

全部代码

```javascript
const Tour = require("../models/tourModels");
const ApiFeature = require("../utils/apiFeature");
//
const catchAsync = (fn) => {
  return async (req, res, next) => {
    fn(req, res, next).catch((err) => {
      next(err);
    });
  };
};

//中间件：查询评分最高且便宜的五个旅行目的地
exports.topCheap5 = (req, res, next) => {
  req.query.limit = 5; //限制查询数据为5条
  req.query.sort = "-ratingsAverage,price"; //选取评分最高的5条，且按照price升序排序
  req.query.filter = "name,price,ratingsAverage,summary"; //限制字段
  next();
};

//获取全部旅游数据
exports.getTours = catchAsync(async (req, res, next) => {
  const feature = new ApiFeature(Tour.find(), req.query)
    .filter()
    .sort()
    .limit()
    .paging();
  //返回查询数据
  const toursAllData = await feature.query;
  // console.log("all data", toursAllData);
  res.status(200).json({
    status: "get success",
    results: toursAllData.length,
    data: { data: toursAllData },
  });
});

//获取指定数据
exports.getTour = catchAsync(async (req, res) => {
  const tourData = await Tour.findById(req.params.id);
  //findById = findOne({_id: id})简写
  res.status(200).json({ status: "get success", data: { data: tourData } });
});

//创建旅游数据
exports.createTour = catchAsync(async (req, res, next) => {
  const tourData = await Tour.create(req.body);
  res.status(200).json({ status: "create success", data: { data: tourData } });
});

//更新数据
exports.updateTour = catchAsync(async (req, res) => {
  const data = await Tour.findByIdAndUpdate(req.params.id, req.body, {
    new: true,
    //开启数据验证
    runValidators: true,
  });
  //new: true返回更新后的数据返回
  //runValidators: 验证更新值的type是否符合要求
  res.status(200).json({ status: "update success", data: { data: data } });
});

//删除数据
exports.delTour = catchAsync(async (req, res) => {
  const data = await Tour.findByIdAndDelete(req.params.id, {
    rawResult: true,
  });
  //rawResult: 返回删除的数据
  res.status(200).json({ status: "delete success", data: { data: data } });
});

exports.tourStats = catchAsync(async (req, res) => {
  const stats = await Tour.aggregate([
    //pipeline
    {
      $match: { ratingsAverage: { $gte: 4 } },
    },
    //stages
    {
      //分组
      $group: {
        //以哪个字段分组，null不分组
        _id: "$difficulty",
        //$sum 求总和
        sum: { $sum: 1 },
        //$avg 求平均数
        ratingAvg: { $avg: "$ratingsAverage" },
        priceAvg: { $avg: "$price" },
        priceSum: { $sum: "$price" },
        minPrice: { $min: "$price" },
        maxPrice: { $max: "$price" },
        name: { $push: "$name" },
      },
    },
    {
      $sort: { ratingAvg: -1 },
    },
  ]);
  res.status(200).json({ status: "success", data: { stats } });
});

//按月份分类数据
exports.tourTime = catchAsync(async (req, res) => {
  const year = req.params.year * 1;
  const tours = await Tour.aggregate([
    {
      //展开文档数据中的数组
      $unwisdnd: "$startDates",
    },
    {
      //匹配数据
      $match: {
        startDates: {
          $gte: new Date(`${year}-01-01`),
          $lte: new Date(`${year}-12-31`),
        },
      },
    },
    {
      //分类
      $group: {
        _id: {
          $month: "$startDates",
        },
        name: { $push: "$name" },
        resultNum: { $sum: 1 },
      },
    },
    {
      //添加属性字段
      $addFields: {
        month: "$_id",
      },
    },
    {
      //控制返回数据字段是否显示： 0 不显示 1 显示
      $project: {
        _id: 0,
      },
    },
    {
      //排序
      $sort: {
        resultNum: -1,
      },
    },
  ]);
  res.status(200).json({ status: "success", data: { data: tours } });
});

```

逻辑：

catchAsync 返回 一个匿名函数

catchAsync 传入一个 async await 函数 fn

匹配到路由时，调用匿名函数，匿名函数调用 fn

fn 等待 await 查询结果, 出错 返回reject 状态的 promise, 成功 继续执行之后代码

catch error 之后，next(err)：next传入error, 调至 express 处理错误的中间件，执行该中间件



##### 5.添加404错误处理

```javascript
const Tour = require("../models/tourModels");
const ApiFeature = require("../utils/apiFeature");
const catchAsync = require("../utils/catchAsync");
const ErrorHanding = require("../utils/errorHanding");

//获取指定数据
exports.getTour = catchAsync(async (req, res, next) => {
  const tourData = await Tour.findById(req.params.id);

  //添加404错误处理
  if (!tourData) {
    return next(new ErrorHanding("tour ID is not found", 404));
  }
  //findById = findOne({_id: id})简写
  res.status(200).json({ status: "get success", data: { data: tourData } });
});

//创建旅游数据
exports.createTour = catchAsync(async (req, res, next) => {
  const tourData = await Tour.create(req.body);
  res.status(200).json({ status: "create success", data: { data: tourData } });
});

//更新数据
exports.updateTour = catchAsync(async (req, res, next) => {
  const data = await Tour.findByIdAndUpdate(req.params.id, req.body, {
    new: true,
    //开启数据验证
    runValidators: true,
  });
  //new: true返回更新后的数据返回
  //runValidators: 验证更新值的type是否符合要求

  //添加404错误处理
  if (!data) {
    return next(new ErrorHanding("tour id is not found", 404));
  }
  res.status(200).json({ status: "update success", data: { data: data } });
});

//删除数据
exports.delTour = catchAsync(async (req, res, next) => {
  const data = await Tour.findByIdAndDelete(req.params.id, {
    rawResult: true,
  });
  //rawResult: 返回删除的数据

  //添加404错误处理
  if (!data) {
    return next(new ErrorHanding("tour id is not found", 404));
  }
  res.status(200).json({ status: "delete success", data: { data: data } });
});


```

✨根据id找不到该数据，则说明该数据不存在，返回404错误



##### 6.根据不同生产环境返回不同错误信息

生产环境面向用户，所以返回的信息需简单易理解

开发环境面向开发，所以错误需详细

由此我们需根据不同的环境返回不同的错误信息

```javascript
//errorHanding.js
class ErrorHanding extends Error {
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode || 500;
    this.status = `${this.statusCode}`.startsWith(4) ? "fail" : " error";
    this.isOperational = true;
    Error.captureStackTrace(this, this.constructor);
  }
}

module.exports = ErrorHanding;

//errController.js
function sendErrorPrd(err, res) {
  //isOperational 用来标记是否为意外错误
  if (err.isOperational) {
    res
      .status(err.statusCode)
      .json({ status: err.status, message: err.message });
  } else {
    //处理未知错误
    res.status(500).json({
      status: "error",
      message: "发生了一些错误",
    });
  }
}

function sendErrorDev(err, res) {
  res.status(err.statusCode).json({
    status: err.status,
    error: err,
    stack: err.stack,
    message: err.message,
  });
}

module.exports = (err, req, res, next) => {
  err.statusCode = err.statusCode || 500;
  err.status = err.status || "error";
  if (process.env.NODE_ENV !== "production") {
    sendErrorPrd(err, res);
  } else if (process.env.NODE_ENV !== "development") {
    sendErrorDev(err, res);
  }
};
```



##### 7.处理mongodb错误

将mongodb错误在生产环境中返回具体错误信息给用户

之前：

```javascript
if (err.isOperational) {
    res
      .status(err.statusCode)
      .json({ status: err.status, message: err.message });
  } else {
    //处理未知错误
    res.status(500).json({
      status: "error",
      message: "发生了一些错误",
    });
  }
```

生产环境中，我们直接将mongodb错误返回，导致在express error 中间件中，err 没有添加 isOperational 属性，因此直接返回未知错误，

现在：

```javascript
if (err.name === "CastError") {
      error = errHandleDB(error);
    }

//处理mongodb错误
function errHandleDB(err) {
  const message = `非法字段 ${err.path}: ${err.value}`;
  // new ErrorHanding 给error 添加了 isOperational 属性值，不为未知错误
  return new ErrorHanding(message, 400);
}
```

我们针对不同的mongodb的错误信息，创建 ErrorHanding 实例，message, 添加 isOperational 属性， 返回响应的错误

```javascript
const ErrorHanding = require("../utils/errorHanding");

//处理mongodb错误
function errHandleDB(err) {
  const message = `非法字段 ${err.path}: ${err.value}`;
  // new ErrorHanding 给error 添加了 isOperational 属性值，不为未知错误
  return new ErrorHanding(message, 400);
}

function sendErrorPrd(err, res) {
  //isOperational 用来标记是否为意外错误
  if (err.isOperational) {
    res
      .status(err.statusCode)
      .json({ status: err.status, message: err.message });
  } else {
    //处理未知错误
    res.status(500).json({
      status: "error",
      message: "发生了一些错误",
    });
  }
}

function sendErrorDev(err, res) {
  res.status(err.statusCode).json({
    status: err.status,
    error: err,
    stack: err.stack,
    message: err.message,
  });
}

module.exports = (err, req, res, next) => {
  err.statusCode = err.statusCode || 500;
  err.status = err.status || "error";
  let error = { ...err };
  if (process.env.NODE_ENV === "production") {
    //处理mongodb错误
    if (err.name === "CastError") {
      error = errHandleDB(error);
    }
    sendErrorPrd(error, res);
  } else if (process.env.NODE_ENV === "development") {
    sendErrorDev(err, res);
  }
};
```